---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u3864172/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R font-awesome-4.7.0 $DEPLOYPATH
